// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210821131003_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Models.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ToDoItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("ToDoListId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItem_Table");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f599c235-6eee-4734-bf73-e81e53692743"),
                            Description = "Wash Shoes",
                            Name = "Laundry",
                            Status = "PENDING",
                            ToDoListId = new Guid("660ed4cd-1361-4216-9faa-9636e4df681a")
                        },
                        new
                        {
                            Id = new Guid("af374b3a-7f95-4fda-9f17-eb368dbd2567"),
                            Description = "Raviolis",
                            Name = "Cook",
                            Status = "PENDING",
                            ToDoListId = new Guid("660ed4cd-1361-4216-9faa-9636e4df681a")
                        },
                        new
                        {
                            Id = new Guid("6d275162-39d8-4d74-b912-5de60172b7c6"),
                            Description = "Carrots, Tomatoes",
                            Name = "Vegetals",
                            Status = "PENDING",
                            ToDoListId = new Guid("410c14e3-e6df-35c8-8c6f-1e19aed675bc")
                        },
                        new
                        {
                            Id = new Guid("2471077e-8c15-4f30-90e2-b945bb4ca8c7"),
                            Description = "Beaf, Bacon",
                            Name = "Meat",
                            Status = "PENDING",
                            ToDoListId = new Guid("410c14e3-e6df-35c8-8c6f-1e19aed675bc")
                        },
                        new
                        {
                            Id = new Guid("da350fe2-00c0-47c8-ac8f-7487426cbf11"),
                            Description = "Budweiser",
                            Name = "Beer",
                            Status = "PENDING",
                            ToDoListId = new Guid("410c14e3-e6df-35c8-8c6f-1e19aed675bc")
                        });
                });

            modelBuilder.Entity("Entities.Models.ToDoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ToDoListId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("ToDoList_Table");

                    b.HasData(
                        new
                        {
                            Id = new Guid("410c14e3-e6df-35c8-8c6f-1e19aed675bc"),
                            CreateDate = new DateTimeOffset(new DateTime(2021, 8, 21, 13, 10, 2, 619, DateTimeKind.Unspecified).AddTicks(8868), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("660ed4cd-1361-4216-9faa-9636e4df681a"),
                            CreateDate = new DateTimeOffset(new DateTime(2021, 8, 21, 13, 10, 2, 619, DateTimeKind.Unspecified).AddTicks(9673), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("Entities.Models.ToDoItem", b =>
                {
                    b.HasOne("Entities.Models.ToDoList", "ToDoList")
                        .WithMany("ToDoItems")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
